default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: street_art_snaps_development

test:
  <<: *default
  database: street_art_snaps_test

production:
  <<: *default
  database: street_art_snaps_production
  username: street_art_snaps
  password: <%= ENV['STREET_ART_SNAPS_DATABASE_PASSWORD'] %>
