# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c763fae57980e79f17745298f5e93ec2a77ce4ff2637d099353bc124ac0cd2472f4afc5729632d49d1920feef47832c69b8429ff112f59cfac8fce6c19a8954

test:
  secret_key_base: 41e7271cd1f86b14393209c35329c3e82b936de0e302289dfa4672f5378e86a612ef2dd9899547cff08d872001a70d35a97b9ac5263ca9220d82246c07fd4d0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
